<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Http\Requests\DecideVerdictApprovalRequest;
use App\Support\ResumesApprovedConversations;
use Fissible\Verdict\Approvals\ApprovalManager;
use Fissible\Verdict\Approvals\ApprovalOutcome;
use Illuminate\Http\RedirectResponse;
use Laravel\Ai\Approvals\Decision;
use Laravel\Ai\Exceptions\ApprovalMismatchException;

/**
 * Generated by verdict:make-approval-flow; the TODOs are replaced with this
 * app's answers. Receipt/conversation ownership: DecideVerdictApprovalRequest
 * verifies the tool call belongs to this app's own conversation store, and
 * only reviewers pass its authorize(). Verdict's challenge excludes raw
 * arguments by design; the screen composes display context from the app's
 * own store instead (ApprovalScreenController).
 */
final class VerdictApprovalDecisionController
{
    public function approve(
        DecideVerdictApprovalRequest $request,
        ApprovalManager $approvals,
        ResumesApprovedConversations $resumes,
    ): RedirectResponse {
        $decisionMaker = $this->decisionMaker($request);

        $transition = $approvals->approve(
            receiptId: $request->string('receipt_id')->toString(),
            toolCallId: $request->string('tool_call_id')->toString(),
            approvedBy: $decisionMaker,
        );

        return $this->respond(
            $request,
            $transition->outcome,
            $transition->succeeded(),
            $resumes,
            Decision::approve(),
        );
    }

    public function reject(
        DecideVerdictApprovalRequest $request,
        ApprovalManager $approvals,
        ResumesApprovedConversations $resumes,
    ): RedirectResponse {
        $decisionMaker = $this->decisionMaker($request);

        $transition = $approvals->reject(
            receiptId: $request->string('receipt_id')->toString(),
            toolCallId: $request->string('tool_call_id')->toString(),
            rejectedBy: $decisionMaker,
        );

        return $this->respond(
            $request,
            $transition->outcome,
            $transition->succeeded(),
            $resumes,
            Decision::reject('The reviewer declined this action.'),
        );
    }

    private function respond(
        DecideVerdictApprovalRequest $request,
        ApprovalOutcome $outcome,
        bool $succeeded,
        ResumesApprovedConversations $resumes,
        Decision $decision,
    ): RedirectResponse {
        if (! $succeeded) {
            // Normal outcomes: not_found, mismatch, expired, and invalid_state. Do not resume.
            return back()->with('verdict_approval_outcome', $outcome->value);
        }

        // Resume only after the durable transition succeeds. laravel/ai rejects a
        // decision for an already-resolved tool call outright — surface that as an
        // outcome rather than a retry (the exactly-once behavior, not an error).
        try {
            $resumes->resume($request->string('tool_call_id')->toString(), $decision);
        } catch (ApprovalMismatchException) {
            return back()->with('verdict_approval_outcome', 'already_resolved');
        }

        return back()->with('verdict_approval_outcome', $outcome->value);
    }

    private function decisionMaker(DecideVerdictApprovalRequest $request): string
    {
        $reviewer = $request->user();

        abort_unless($reviewer !== null, 403);

        return 'user:'.(string) $reviewer->getAuthIdentifier();
    }
}
